sudo: required
services:
  - docker


before_install:
    - docker build -t ashishdhawal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ashishdhawal/docker-react-wsl npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react-wsl 
  env: DockerReactWsl-env
  bucket_name: "elasticbeanstalk-us-east-2-171912905752"
  bucker_path: docker-react-wsl
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

